//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionarretecaisse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billet
    {
        public string Id_billet { get; set; }
        public double valeur { get; set; }
        public string creer_par { get; set; }
        public string modifier_par { get; set; }
        public string date_creation { get; set; }
        public string date_modification { get; set; }
    
        public virtual nb_billet nb_billet { get; set; }
    }
}
