//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionarretecaisse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class demande
    {
        public string Id_demande { get; set; }
        public string date_demande { get; set; }
        public double montant { get; set; }
        public string source_demande { get; set; }
        public string distination_demande { get; set; }
        public string etat { get; set; }
    
        public virtual caisse caisse { get; set; }
        public virtual caisse caisse1 { get; set; }
    }
}
