//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionarretecaisse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionEntities : DbContext
    {
        public GestionEntities()
            : base("name=GestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agence> agence { get; set; }
        public virtual DbSet<billet> billet { get; set; }
        public virtual DbSet<caisse> caisse { get; set; }
        public virtual DbSet<compte> compte { get; set; }
        public virtual DbSet<demande> demande { get; set; }
        public virtual DbSet<Direction> Direction { get; set; }
        public virtual DbSet<mouvement> mouvement { get; set; }
        public virtual DbSet<nb_billet> nb_billet { get; set; }
        public virtual DbSet<op_profil> op_profil { get; set; }
        public virtual DbSet<operation> operation { get; set; }
        public virtual DbSet<profil> profil { get; set; }
        public virtual DbSet<Trace> Trace { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
    }
}
