//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionarretecaisse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nb_billet
    {
        public string Id_billet { get; set; }
        public string id_caisse { get; set; }
        public Nullable<int> nombre { get; set; }
    
        public virtual billet billet { get; set; }
        public virtual caisse caisse { get; set; }
    }
}
