//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionarretecaisse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class op_profil
    {
        public string id_profil { get; set; }
        public string id_operation { get; set; }
        public string id_op_profil { get; set; }
    
        public virtual operation operation { get; set; }
        public virtual profil profil { get; set; }
    }
}
