//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestionarretecaisse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trace
    {
        public int Id_trace { get; set; }
        public string id_caisse { get; set; }
        public System.DateTime date_trace { get; set; }
        public string ajuster_par { get; set; }
        public Nullable<double> ecart { get; set; }
        public Nullable<double> montant_saisir { get; set; }
        public string operation { get; set; }
    
        public virtual caisse caisse { get; set; }
    }
}
